$(document).ready(function(){
    $("#showRegisterDiv").click(function(){
        $("#logInDiv").hide();
        $("#registerDiv").show();
    });
    $("#showLogInDiv").click(function(){
        $("#logInDiv").show();
        $("#registerDiv").hide();
    });
     $("#showMore").click(function(){
        $(".newsLeftColumn").css('display','block');
    });
    $(".close").click(function(){
        $(".newsLeftColumn").css('display','none');
    });   
});
